### ISSUE TITLE
Example of geokey data on a map

### ISSUE THREAD

**Issue by pmackay** [ExCiteS/geokey#202]
Try as I might, I cannot find an example map or application that would be using GeoKey as a backend data store, which I assume is the intent. Could you please add any relevant examples to the docs?

**Comment by mfc-julius** [comment]
https://communitymaps.org.uk currently uses GeoKey as a back-end. Unfortunately, it is not open sourced.

Yet another project (and even open source) using GeoKey is https://github.com/NatEvatt/Angular-GeoKey by @NatEvatt.
