### ISSUE TITLE
tests fail on no hstore extension

### ISSUE THREAD

**Issue by bcfuchs** [ExCiteS/geokey#234]
the test db doesn't create an hstore extension. 

solution:
psql template1 -c 'create extension hstore;'

a la the docs for django_hstore. http://djangonauts.github.io/django-hstore/#_running_tests 

Tho this might be overkill. A hook in the test setup would be better...

**Comment by oliverroick** [comment]
Switched from hstore to jsonb in the next version, this will not be relevant any longer
