### ISSUE TITLE
Path to "assets"

### ISSUE THREAD

**Issue by mfc-julius** [ExCiteS/geokey#244]
Current default configuration sets "assets" dir inside the GeoKey app directory:
`MEDIA_ROOT = normpath(join(SITE_ROOT, 'assets'))`

To set "assets" inside the main directory, I used:
`MEDIA_ROOT = normpath(join(dirname(dirname(abspath(__file__))), 'assets'))`
This uses the parent directory of a current file (settings.py), and then adds "assets".

**Comment by oliverroick** [comment]
Thanks that's added now
