### ISSUE TITLE
500 error when changing comment status to "resolved"

### ISSUE THREAD

**Issue by mfc-julius** [ExCiteS/geokey#246]
AttributeError at /api/projects/9/data-groupings/all-contributions/contributions/77/comments/187/

'NoneType' object has no attribute 'get'

/usr/local/geokey/geokey/contributions/models.py in update_display_field, line 230

**Comment by oliverroick** [comment]
Fixed in https://github.com/ExCiteS/geokey/commit/1e7969f3a25e4e8c2b778414b13c64fd1d089968
