### ISSUE TITLE
Keep static CSS/JS libraries up-to-date

### ISSUE THREAD

**Issue by juliusosokinas** [ExCiteS/geokey#256]
Maybe npm or Bower could help.

**Comment by mfc-julius** [comment]
Current version of bootstrap-fileinput is outdated, also it has bugs when setting min and max image dimensions.

**Comment by oliverroick** [comment]
Are min and max image dimensions used on our side?

**Comment by mfc-julius** [comment]
I'd like to try to add some additional checks when uploading images on the extension. Also, I noticed it's way outdated, and to check if the newer version works well for our needs should not be a big deal.

**Comment by juliusosokinas** [comment]
Some required dependencies updated.
