### ISSUE TITLE
Possible own test suite runner

### ISSUE THREAD

**Issue by mfc-julius** [ExCiteS/geokey#259]
Unit tests still require hstore to be applied on the test database. Otherwise tests won't work.

Maybe there's a way to create own test suite runner, like in the example: http://stackoverflow.com/questions/16355895/installing-hstore-extension-in-django-nose-tests

**Comment by oliverroick** [comment]
Creating a custom test suite runner would be overkill to solve such a minor problem, especially since we plan to move everything from hstore to jsonb soon

For now, you can create the extension, which solves the problem:

```
psql -d template1 -c 'create extension hstore;'
```
