### ISSUE TITLE
Prepare for 0.10 release

### ISSUE THREAD

**Issue by oliverroick** [ExCiteS/geokey#267]
- [x] Outsource daily digest emailing (this is a very specific Community Maps feature and should be handled in the plugin or a specific daily digest plugin with customisable email templates)
- [x] Revise footer area in admin panel (It should have a link to the website, the help and API docs, twitter, etc.
- [x] DRY-out contexts from views into `geokey.core.views`
- [x] Upgrade dependencies
- [x] Update project website
- [x] Design project info
    - [x] Private/Public
    - [x] who contributes
    - [x] created by
    - [x] created when

**Comment by mfc-julius** [comment]
+1 for merging Location + Observation = Contribution (and naming would be more meaningful in the code).

**Comment by mstevens83** [comment]
Why 0.10 instead of 1.0?
v1.0 sound so much better mate :-)

**Comment by juliusosokinas** [comment]
There is a bit more work I want to do on GeoKey for the first official version v1 to be released. On the 0.10 I will just add additional functionality which we need, nothing else.

**Comment by juliusosokinas** [comment]
Additional tasks:

- [ ] Extend KML rendered to support media files
- [ ] Add CSV parser
