### ISSUE TITLE
Personal info is exposed on the response of subsets

### ISSUE THREAD

**Issue by mfc-julius** [ExCiteS/geokey#269]
This includes, the date creator of a subset joined, email, etc., even password hash.

**Comment by oliverroick** [comment]
Do we need creator anyway? It's not on any other ressource, e.g. projects, categories, fields.

**Comment by mfc-julius** [comment]
I won't be using on CM, it's up to you to include this info, or not.

**Comment by oliverroick** [comment]
Added this to https://github.com/ExCiteS/geokey/pull/268
