### ISSUE TITLE
Numbers of media and comments are incorrect

### ISSUE THREAD

**Issue by mfc-julius** [ExCiteS/geokey#273]
On the latest update, the counts are wrong (I thought it was including deleted media and comments, but at the end I didn't know what is it counting).

**Comment by oliverroick** [comment]
Any examples?

**Comment by mfc-julius** [comment]
http://client.geokey.org.uk/#/project/9/contribution/5016?center=51.5007:-0.1246:19&tab=1

That's the first contribution in the list. Take a look what is shows when in the list, and what when contribution is opened.
