### ISSUE TITLE
Add another subset after the one has been created

### ISSUE THREAD

**Issue by juliusosokinas** [ExCiteS/geokey#280]
Currently there's no obvious way how to access "Create new subset" when you just created one.

That is, when you create a subset, you land on it's Data page. From there, you can change how data is collected for the subset, you can access subset's settings. But there is no button to add new subset, also no button to go back to a list of all subsets. I know now that the Subset tab is always clickable, but once on it, it's not always obvious that you would need to click it again to go to the list of subsets.

**Comment by mfc-julius** [comment]
I will update GeoKey Community Maps extension later on, to match the new design. And for accessing nested views, I was thinking about breadcrumbing: http://getbootstrap.com/components/#breadcrumbs (adding after the snippet message). For example:

```
<ol class="breadcrumb">
  <li><a href="#">All brands</a></li>
  <li><a href="#">Brand sponsors</a></li>
  <li class="active">Add new sponsor</li>
</ol>
```

This would allow users easily so access any point of the nested views. Also, to see where exactly user is.
