### ISSUE TITLE
"Contribution update" state

### ISSUE THREAD

**Issue by mfc-julius** [ExCiteS/geokey#283]
I've noticed, that deleting a comment results in a "updated by" change of a contribution. Though, adding a comment does't. Or I can't reproduce it, but weird thing happens here: https://southwark.communitymaps.org.uk/#/project/15/contribution/3234?center=51.4802:-0.0868:18&tab=3 As you can see, some registered user left a comment and it resulted "updated by" change of a contribution.

**Comment by oliverroick** [comment]
That's a bug. The contribution is updated when there are no review comments assigned to it. That should not happen, when the contribution's status is anything other that `review`.

You can fix the issue here: https://github.com/ExCiteS/geokey/blob/master/geokey/contributions/views/comments.py#L178

**Comment by mfc-julius** [comment]
But maybe it's a good thing? When a comment or media file is added, this results in a contribution update, automatically contribution is the first in the list? Because there's no other way of knowing what contributions are being commented on, this could result in user conversation.

**Comment by oliverroick** [comment]
I don't know. It's not an update to the contribution, because nothing changes in the contribution itself. If you want to integrate new comments and uploaded files in the order of contributions, this should be implemented in a different way, e.g. displaying a flag in the list on client side.
