### ISSUE TITLE
django_nose requirement

### ISSUE THREAD

**Issue by mfc-julius** [ExCiteS/geokey#285]
django_nose is required when running migrations on a fresh install, although on the app it's listed as a dev requirement and is not being installed by default.

**Comment by oliverroick** [comment]
Only when you use dev settings. 

If you install for production, you have to import `geokey.core.settings.prod` instead of `geokey.core.settings.dev` in `settings.py`

**Comment by mfc-julius** [comment]
The example settings from GitHub repo has the "dev" settings, but also the http://geokey.org.uk/downloads/settings.tar.gz has the same "dev" enabled. And if to follow install instruction on the website: http://geokey.org.uk/help/how-to-install.html there's nothing written about changed "dev" to "prod".

**Comment by oliverroick** [comment]
Well then, add it to the docs!

**Comment by oliverroick** [comment]
You can also change the example settings to `prod` in the tar ball.
