### ISSUE TITLE
Running tests removes user uploaded images!

### ISSUE THREAD

**Issue by juliusosokinas** [ExCiteS/geokey#302]
Also, leaves a bunch of test images inside the "symbols" folder.

**Comment by oliverroick** [comment]
Some tests empty the user-uploads directories after they were run. Otherwise you end up with loads of images after each test

**Comment by mfc-julius** [comment]
Yeah but they also break my contributions with media files, because the server then returns 500 when accessing them.

So supposedly it's better to remove those test files one by one when they're not needed anymore, or remove only the ones that starts with "test...".

**Comment by oliverroick** [comment]
You could use different settings for tests. Import the dev settings and overwrite the directory for user uploads. That way you have independent directories for server and tests.

Run the tests using the `--settings` flag
