### ISSUE TITLE
Update to Django v1.9.x (low priority)

### ISSUE THREAD

**Issue by mstevens83** [ExCiteS/geokey#332]
Django v1.9.x has been out for a while and I was wondering if there is a particular reason why we are sticking to v1.8.x (see https://requires.io/github/ExCiteS/geokey/requirements/?branch=master).

@oliverroick ?
@juliusosokinas ?

**Comment by juliusosokinas** [comment]
Django 1.8 is a long-term support release, though 1.9 is not. That is, even 1.9 was released later, 1.8 will get supported patches for a longer time.

See: https://www.djangoproject.com/weblog/2015/jun/25/roadmap/

**Comment by mstevens83** [comment]
Ok that makes sense.
