### ISSUE TITLE
Prepare for 0.9 release

### ISSUE THREAD

**Issue by mstevens83** [ExCiteS/geokey#333]
Please add blockers for 0.9.0 release below:

- [x] Extensions can `register` their version
- [x] `deregister` method (for testing purposes only)
- [x] Add & document core Info API (`api/info/`)
- [x] Audio file support
- [x] Value-based symbology mode for categories:
    - [x] Add optional `symbol` `ImageField` to `LookupValue` model
    - [x] Add optional `symbol` `ImageField` to `MultipleLookupValue` model
    - [x] Add admin pages support for viewing/changing/deteling `(Multiple)LookupValue` symbols (https://github.com/ExCiteS/software-dev/issues/76)
    - [ ] ~~Add admin pages support for setting category display mode to be based on the symbol of a `(Multiple)LookupField` (possibly with a colour or category-wide symbol as fall-back)~~
- [x] Add possibility to lock projects
- [x] Write a blog post about 0.9 release
- [x] Up-to-date dependencies

**Comment by juliusosokinas** [comment]
Make draft blog post (GeoKey website) and add things you've done, I will add mine and publish when 0.9 is released.

Not sure if I manage to finish everything until you leave.

**Comment by mstevens83** [comment]
I saw you deleted the `lookupvalue-symbology` branch. Did you fully merge it into master?

**Comment by mstevens83** [comment]
Ok nevermind, I found it. I was not looking far enough back :-)
https://github.com/ExCiteS/geokey/commit/8fbe08a5b91489b0e40e66a202ead596d08d1053

**Comment by juliusosokinas** [comment]
Yes, everything's on master now. I'll do a 0.9 release later today or tomorrow early morning.

**Comment by mstevens83** [comment]
Great!

**Comment by juliusosokinas** [comment]
Great job, thanks @mstevens83 :+1:

**Comment by mstevens83** [comment]
You too @juliusosokinas  ;-)
