### ISSUE TITLE
Support Django 1.10 and start testing with 1.11

### ISSUE THREAD

**Issue by ghost** [ExCiteS/geokey#379]
First thing needed is django-hstore to support these Django versions.

There was a pull request on the library, but it [broke tests](https://travis-ci.org/djangonauts/django-hstore). Also, apparently library is [not maintained anymore](https://github.com/djangonauts/django-hstore/issues/161). @sliob have a look and try to resolve the issues.

**Comment by edwardgalligan** [comment]
Looks from a recently pushed branch that @JamesBradbury is working on this. I'm wondering if you need help testing this and/or how near you might be to merging/testability?

**Comment by JamesBradbury** [comment]
Yes I'm working on it when I get a free moment. 

The aim is to upgrade to 1.11 as it has long term support. I don't know how important it is to support intermediate releases as well.

The only real roadblock remaining is the migrations. If you have suggestions about resolving these issues, let me know.

**Comment by edwardgalligan** [comment]
> *I don't know how important it is to support intermediate releases as well.*

Not at all I would imagine? All 1.x documentation has been 1.10+ for a long long time now, so from our perspective things like the middleware changes, etc. have been minor annoyances where simple 1.11 support and nothing else would be preferable.

> *The only real roadblock remaining is the migrations. If you have suggestions about resolving these issues, let me know.*

I saw 138f1cbcdd30afe726d10807d20403fafa133009 - this hasn't been sufficient I presume?

I've been reluctant to sink time into testing that branch myself (if you're in the middle of things and are planning / aware of fixes for outstanding issues), and it's a lot of changes to review by eye. I can have a go next week though if it's at a roadblock.

**Comment by JamesBradbury** [comment]
I would prefer to only support 1.11, but I am checking with other users as it may force changes on others' components.

No, that change did help, but the socialinteraction migration (which I can't find) seems to rely on one from projects. 

`django.db.migrations.exceptions.InconsistentMigrationHistory: Migration socialinteractions.0001_initial is applied before its dependency projects.0002_auto_20180328_1513 on database 'default'.`

**Comment by edwardgalligan** [comment]
> *I am checking with other users as it may force changes on others' components.*

Yeah, worthwhile. I was somewhat selfishly referring to our use only. We have components with a hard dependency on <1.10 but they're self-written and I would have preferred writing for 1.10 initially. Altering will be quick.

I haven't looked at socialinteractions code yet since it was added (not something we'll use/need), but I'll try and have a look at the migrations on Monday. Could that feature be broken out as a DjangoApp or is it very large?

**Comment by josokinas** [comment]
Django v1.11 is now supported in the latest version.
