### ISSUE TITLE
Mention django GEOS bug in README

### ISSUE THREAD

**Issue by edwardgalligan** [ExCiteS/geokey#393]
Just ran across a django bug with parsing GEOS version numbers that causes the application to crash on startup. It's documented here: https://code.djangoproject.com/ticket/28441

The fix is either upgrading to Django 1.11 (#379) or downgrading GEOS to 3.6.1 (as later versions trigger the django bug).

Might be worthwhile sticking a note about the downgrade workaround in the README until #379 is resolved (I'll submit a PR).

**Comment by josokinas** [comment]
Closing this as latest GeoKey version now supports Django version 1.11 🥇
