### ISSUE TITLE
ERROR: Cannot locate specified Dockerfile: ./geokey/Dockerfile

### ISSUE THREAD

**Issue by caduguedess** [ExCiteS/geokey#435]
When trying to do the first step, as the tutorial says, "Pull and extract relevant images, build the GeoKey application container" it donwloads and extracts all the files but gives the error in the tittle.
![erro1](https://user-images.githubusercontent.com/51020710/58370976-4877d680-7ee3-11e9-8a61-eb470e2f2dcc.png)

**Comment by caduguedess** [comment]
If it matters, my system is Windows 10 Home 64 bit, i7 8550U, 16 GB RAM

**Comment by caduguedess** [comment]
I solved that problem by deleting the zipped folder of geokey, only left the unzipped one.
Now the first step is done sucessfully, but in the second step it gives the following error:
ERROR: No container found for geokey_1
I'm using the same folder that I tracked when I did the step 1, is it right?

**Comment by josokinas** [comment]
@caduguedess, you should run the command from within the extracted folder or cloned repository. The 2nd step must be run in a separate terminal window whiles the 1st window is still running.
